# Generated by Django 5.2.6 on 2026-09-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_olympiad_capacity_olympiad_level_result_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deadline', 'Дедлайн через сутки'), ('olympiad', 'Олимпиада завтра')], max_length=12)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_reminders', to='core.registration')),
            ],
            options={
                'verbose_name': 'Отправленное напоминание',
                'verbose_name_plural': 'Отправленные напоминания',
                'constraints': [models.UniqueConstraint(fields=('registration', 'kind'), name='unique_registration_telegram_reminder')],
            },
        ),
    ]
