# Generated by Django 5.2.6 on 2026-09-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_telegramreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='source_key',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Ключ записи источника'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='source_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Синхронизировано'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='format',
            field=models.CharField(blank=True, choices=[('online', 'Онлайн'), ('offline', 'Офлайн'), ('hybrid', 'Гибрид')], default='', max_length=10, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='max_grade',
            field=models.PositiveSmallIntegerField(blank=True, default=11, null=True, verbose_name='По класс'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='min_grade',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True, verbose_name='С класса'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн регистрации'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала'),
        ),
    ]
