# Generated by Django 5.2.6 on 2026-09-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_olympiad_source_key_olympiad_source_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='event_type',
            field=models.CharField(choices=[('olympiad', 'Олимпиада'), ('hackathon', 'Хакатон'), ('contest', 'Конкурс'), ('quiz', 'Викторина'), ('other', 'Другое')], default='olympiad', max_length=12, verbose_name='Тип события'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Демонстрационная запись'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='registration_url',
            field=models.URLField(blank=True, verbose_name='Ссылка для регистрации у организатора'),
        ),
    ]
