# Generated by Django 5.2.6 on 2026-09-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_olympiad_event_type_olympiad_is_demo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='level',
            field=models.CharField(blank=True, choices=[('school', 'Школьный'), ('district', 'Районный'), ('city', 'Городской'), ('regional', 'Областной'), ('national', 'Республиканский'), ('international', 'Международный')], default='', max_length=24, verbose_name='Уровень'),
        ),
    ]
