"""Display translations for the existing educational catalogue, not DB rewrites."""
EVENT_TEXT = {
    "Республиканская олимпиада по информатике": ["National Computer Science Olympiad", "Информатикадан республикалық олимпиада"],
    "Жас математик 2026": ["Young Mathematician 2026", "Жас математик 2026"],
    "English Challenge": ["English Challenge", "Ағылшын тілі сайысы"],
    "Открытая олимпиада по физике": ["Open Physics Olympiad", "Физикадан ашық олимпиада"],
    "Турнир юных химиков": ["Young Chemists Tournament", "Жас химиктер турнирі"],
    "Биология: исследовательский этап": ["Biology: Research Stage", "Биология: зерттеу кезеңі"],
    "Олимпиада по географии Казахстана": ["Kazakhstan Geography Olympiad", "Қазақстан географиясы олимпиадасы"],
    "Юный историк": ["Young Historian", "Жас тарихшы"],
    "Лингвистический марафон": ["Linguistics Marathon", "Лингвистикалық марафон"],
    "Олимпиада по казахскому языку": ["Kazakh Language Olympiad", "Қазақ тілінен олимпиада"],
    "Младшая олимпиада по математике": ["Junior Mathematics Olympiad", "Кіші сыныптарға арналған математика олимпиадасы"],
    "Алгоритмический старт": ["Algorithmic Start", "Алгоритмдік бастау"],
    "Олимпиада по астрономии": ["Astronomy Olympiad", "Астрономия олимпиадасы"],
    "Экология и устойчивое развитие": ["Ecology and Sustainable Development", "Экология және тұрақты даму"],
    "Олимпиада по финансовой грамотности": ["Financial Literacy Olympiad", "Қаржылық сауаттылық олимпиадасы"],
    "Кибербезопасность для школьников": ["Cybersecurity for School Students", "Оқушыларға арналған киберқауіпсіздік"],
    "Инженерная олимпиада": ["Engineering Olympiad", "Инженерлік олимпиада"],
    "Олимпиада по естествознанию": ["Natural Science Olympiad", "Жаратылыстану олимпиадасы"],
    "Открытая олимпиада по английскому языку": ["Open English Language Olympiad", "Ағылшын тілінен ашық олимпиада"],
    "Дебаты: школьная лига": ["Debate: School League", "Пікірсайыс: мектеп лигасы"],
    "Green City: школьный хакатон": ["Green City: School Hackathon", "Green City: мектеп хакатоны"],
    "EdTech Weekend": ["EdTech Weekend", "EdTech демалыс күндері"],
    "Конкурс научных проектов": ["Research Projects Contest", "Ғылыми жобалар байқауы"],
    "Робототехнический хакатон": ["Robotics Hackathon", "Робототехника хакатоны"],
    "Школа-лицей № 72": ["School-Lyceum No. 72", "№ 72 мектеп-лицейі"],
}
